### ISSUE TITLE
Incorrect date in paragraph

### ISSUE THREAD

**Issue by SoCuul** [nohello-net/site#129]
For some reason, the date in the following text is reflected as 2022, when the new year has rolled around!

> But it's 2022 and chat is neither of those things.

**Comment by igorrocha** [comment]
I was looking over the code to see if I could submit a PR fixing this, but it seems that #29 changed how the current year is set, getting it at build time instead of real time.

A new deploy should fix this, so probably any PR being merged will address this issue.
