### ISSUE TITLE
Translate site to Portugue (Brazil)

### ISSUE THREAD

**Issue by angeliski** [nohello-net/site#20]
I want to help to translate to portuguese (pt-br).

I submited a request in transifex :)

**Comment by notjosh** [comment]
Cool! I've accepted the request for Portuguese. It says:

> Your changes on project languages have been saved. Some of the languages cannot be translated by the assigned team's collaborators.

So I'm not sure if I need to invite you as the collaborator..? This is the first time I've had a public project on Transifex.

**Comment by angeliski** [comment]
Idk either xD 
But I will try join the team to see what's will happen

**Comment by Dafrok** [comment]
I submited a Chinese(zh-cn) request too, and the same issue I have met.

**Comment by notjosh** [comment]
@Dafrok I've approved the request! I'm still not sure if that also allows you to edit, or if that's a separate step. Let me know!

**Comment by angeliski** [comment]
@notjosh Is any request pending in your side? I can't join again and I don't have nohello projet ready to me translate. Could you check?

**Comment by Dafrok** [comment]
@notjosh Yes it is a separate step, I've another request to join your team.

**Comment by notjosh** [comment]
Oh my god, I finally found the pending requests. I've accepted all the requests to collaborate - sorry it took so long to find that page! I only got notifications about the _language_, but not the _people_.

I'll need help from some of you deciding what (sub?)languages are important to use on the site. i.e. can we use just `pt`, or should we have both `pt-BR` _and_ `pt-PT`. For English, I only think we need `en`, but it might be different in other languages?

**Comment by angeliski** [comment]
The translation in portuguese is done (people are really fast, I didn't have time to translate any word). But I don't know the next steps. We see a `Unreviewed` section, but I can't perform an action there.

About the languages @notjosh , I think is better use pt-br/pt-pt, just for improve the localization experience, some words are different and could lead to a misunderstanding

**Comment by doceazedo** [comment]
> The translation in portuguese is done (people are really fast, I didn't have time to translate any word). But I don't know the next steps. We see a `Unreviewed` section, but I can't perform an action there.

Hey, I guess that was me. We were probably accepted as collaborators at the same time and we both started working right away. You did a great job with your translations, as I finished the ones I was doing I took the opportunity to make some one-off changes in some of your strings, most of them just for consistency.

But yeah, as you said, it's all properly translated by now, just waiting to be reviewed. I'm not sure how the maintainers are going to do that, but it would be great if you could assess the strings i submitted as I did to yours to make sure everything is ok to go to production.

**Comment by notjosh** [comment]
> About the languages @notjosh , I think is better use pt-br/pt-pt, just for improve the localization experience, some words are different and could lead to a misunderstanding

Cool, yeah, agreed. That would mean figuring out the correct fallbacks, i.e. if we have `de-de` and `de-at`, what should a `de-ch` visitor see? I think something like [ilib-localematcher](https://www.npmjs.com/package/ilib-localematcher) has solved this already, so hopefully easy enough to integrate. If you have any other resources or suggestions, I'd love to take a look.

> But yeah, as you said, it's all properly translated by now, just waiting to be reviewed. I'm not sure how the maintainers are going to do that, but it would be great if you could assess the strings i submitted as I did to yours to make sure everything is ok to go to production.

Honestly, I'll probably mark every contributor/translator as a reviewer. You folks know the languages better than I do :)

**Comment by notjosh** [comment]
Okie doke, I've just made everyone reviewers. It might turn out to be chaos :) but mostly I expect we'll be respectful

**Comment by dzshn** [comment]
hi! I put some feedback there too, I think it's all nicely translated!

**Comment by angeliski** [comment]
I think we are ready to go @notjosh, I just reviewed the last two strings

**Comment by guigomesa** [comment]
Hey @notjosh, i reviewed the pt-br translations and they are ok.

**Comment by hdias2310** [comment]
@notjosh I can help in PT-BR translations/reviews too, my request to join is pending in transifex 😃

**Comment by andreaflether** [comment]
> > The translation in portuguese is done (people are really fast, I didn't have time to translate any word). But I don't know the next steps. We see a `Unreviewed` section, but I can't perform an action there.
> 
> Hey, I guess that was me. We were probably accepted as collaborators at the same time and we both started working right away. You did a great job with your translations, as I finished the ones I was doing I took the opportunity to make some one-off changes in some of your strings, most of them just for consistency.
> 
> But yeah, as you said, it's all properly translated by now, just waiting to be reviewed. I'm not sure how the maintainers are going to do that, but it would be great if you could assess the strings i submitted as I did to yours to make sure everything is ok to go to production.
> 
> EDIT: I just noticed that are more than 2 people that contributed with pt-BR translations, so maybe something I said was not meant to you (I'm too confused at this point haha). Anyways, it would still be nice to have every string reviewed by other Portuguese speaking people.

That was probably me! I could see you translating at the same time as me, haha. You did an awesome job with your translations. I'm glad we could help in this project :)

**Comment by edmilsonrobson** [comment]
It seems like the ptBR translations are done and very well-reviewed. Is there any way to contribute to actually getting those translations to show on the website? I read it requires some manual work too.

Btw ptBR and pt are (IMO) worth having their own translations, but redirecting people from Portugal to our `ptBR` translation is an acceptable thing too.

**Comment by georgebrindeiro** [comment]
BRAZIL NEEDS THIS!

Thanks to everyone who contributed. Let's get this shipped 🚀

**Comment by angeliski** [comment]
Hey @notjosh any news here? Do you need help in any topic?

**Comment by notjosh** [comment]
https://nohello.net/pt-br/ 🥳 

Sorry it took so long, I got super busy on some other things.
