### ISSUE TITLE
How do you do the retyping of the hello in different languages?

### ISSUE THREAD

**Issue by jaysharm** [nohello-net/site#22]
Forgive me as this is not an issue, more of a question.

The cursor and retyping of hello then backspaced, then retyped in a different language, then backspaced etc... is awesome, how is it done?  Can you point me to the code?

I'm a software developer but I don't design websites so I'm sorry if this is a basic question.

**Comment by notjosh** [comment]
No problem!

The library we use is [Typed.js](https://github.com/mattboldt/typed.js/), which has a reasonably simple JavaScript API:

```html
<div id="foo"></div>

<script>
var options = {
  strings: ['first', 'second', 'third'],
  typeSpeed: 40
};

var typed = new Typed('#foo', options);
</script>
```

It also has some neat options to embed the strings in HTML:

```html
<div id="typed-strings">
  <p>first</p>
  <p>second</p>
  <p>third</p>
</div>

<span id="foo"></span>

<script>
var typed = new Typed('#foo', {
  stringsElement: '#typed-strings'
});
</script>
```

An alternative, if you want something where you only need to write HTML, could be [Typer.js](https://steven.codes/typerjs/). It has a couple of examples that make it pretty easy to integrate.

Hope that helps!
