### ISSUE TITLE
Problem with the [year][/year] tags in translation

### ISSUE THREAD

**Issue by doceazedo** [nohello-net/site#23]
When using the `[year][/year]` tags in the string [409955021](https://www.transifex.com/nohello/nohellodotnet/translate/#pt_BR/messages-en/409955021), they look like this in English:
- `(dynamic / aff)` But it's 2022 and chat is neither of those things.
- `(static / neg)` But it's not 1990 and chat is neither of those things.

The problem is that the affirmative and negative forms in pt-BR are quite different and can't fit in this format:
- `(aff)` Mas estamos em 2022 e conversar por texto não funciona dessa forma.
- `(neg)` Mas **não** estamos **mais** em 1990 e conversar por texto não funciona dessa forma.

Stuff like this happens all the time in localisation (plural and nouns can be trick in German, for example).

If the maintainers are willing to fix this in the code, I would suggest to have this entire phrase as a single string and have a note for its context (as it belongs in the middle of a paragraph).

If they are not, I think it's better to go for only using the static/negative form and ignoring the `[year]` tag in pt-BR. This is the original suggestion submitted by Andréa and I'm inclined to agree. I changed it anyway to use the `[year]` tag with "2022" as the placeholder as we discuss this and as I don't know if the code would break because it expects the tag to exist (Transifex warns that it is missing).

**Comment by notjosh** [comment]
Ah, you make an excellent point, and I kinda expected this to happen :P 

I'd guess something with entire separate strings would work. Something like:

```sh
# original string, with placeholder clearly marked:
body: "... and that's great! [placeholder]But it's not 1990 and chat is neither of those things.[/placeholder] For most people ..."

# content to dynamically put into placeholder
placeholder-content: "But it's [year] and chat is neither of those things."
```

Then again, now that the site is using an SSG, we can don't really need the placeholder with client side replacement anymore...so it's probably easier for translators if we just skip the placeholder sentence entirely. We'd still need a "[year]" placeholder, but that's much simpler.

I'll have a think and change it tomorrow.

**Comment by notjosh** [comment]
Ok, it took a couple of days, but #29 removed the placeholder. Hopefully that makes the translation easier now, if you wouldn't mind checking. If it works better, I'll start publishing the new languages on the site. Thanks!

**Comment by doceazedo** [comment]
That's perfect! I translated and self-reviewed the strings that were changed, as they were already previously reviewed and the changes were small. With that said, the pt-BR language is ready to be shipped :)

**Comment by notjosh** [comment]
Okay, pt-BR shipped, so I'm gonna close this. Thanks!
