### ISSUE TITLE
Add Czech

### ISSUE THREAD

**Issue by MegamiShin** [nohello-net/site#36]
Please add the Czech language to Transifex, it's requested but not there yet.
I would love to translate it, as there are many people who really need this site linked to them...

**Comment by notjosh** [comment]
I've added it to Transifex! Let me know when you've got it translated, and I'll push it live :)

**Comment by MegamiShin** [comment]
@notjosh Hi, I made a request to join the team, please accept it.

**Comment by notjosh** [comment]
Thanks for the bump! Accepted the invitation just now :)

**Comment by MegamiShin** [comment]
@notjosh Thanks, I have finished the translation. :)

**Comment by notjosh** [comment]
This translation is now live: https://nohello.net/cs/ !

Děkujeme!

**Comment by MegamiShin** [comment]
Hi, @notjosh , thank you so much for the opportunity, but I Have a question. Would you be ok with me putting nohello.net on my translation portfolio? I'd like to make translation a side job but I dont Have a portfolio, it would help me a lot. All I need is your approval.

Thanks!

**Comment by notjosh** [comment]
Sure, that's no problem. Just make sure you take a screenshot(/PDF) in case someone else contributes more translations, so you'll know exactly what is yours! :)

**Comment by MegamiShin** [comment]
Yes, thank you so much.
