### ISSUE TITLE
Fixed translation errors

### ISSUE THREAD

**Issue by MegamiShin** [nohello-net/site#45]
Hi @notjosh ,
I reviewed the live translation from yesterday and I noticed some errors, sorry for making them, I really didn't notice them when I was translating it.
I have updated the translation on Transifex, if you're not busy, could you please update the site too?
Don't worry, I reviewed the full translation and everything should be good now. 😄 
Thanks!

**Comment by notjosh** [comment]
Thanks! Changes are now live: https://nohello.net/cs/
