### ISSUE TITLE
Add Italian

### ISSUE THREAD

**Issue by manuel-uberti** [nohello-net/site#51]
Hi, 

first of all thanks for this lovely website. I just added the Italian translation on Transifex, but I'm not sure what more I need to do now for it to be ready for you.

Let me know.

**Comment by notjosh** [comment]
I've added the translations, and pushed them live: https://nohello.net/it/

Grazie!

**Comment by Wiccio** [comment]
Thank you for adding the Italian language, but there are a few errors. I will correct the problematic sentences below.

```
Imagine calling someone on the phone, going hello! then putting them on hold...
Immagina di chiamare qualcuno al telefono, dire ciao! e lasciarlo in attesa...
```
```
Just ask the question!
Scrivi subito la domanda!
```
```
If you feel it's a bit brusque to simply say "Hi" and ask the question, you can still preface your message with as many pleasantries as you see fit.
Se ti sembra un po’ brusco dire semplicemente “Ciao” e poi porre la domanda, puoi comunque precedere il messaggio con tutte le formule di cortesia che preferisci.
```
```
When done right - everyone's happy! 
Se fatto nel modo giusto, tutti sono contenti!
```

In addition, the year should be made dynamic rather than left as plain text, as it still says “2022”.
