### ISSUE TITLE
Polish translation has incorrect name

### ISSUE THREAD

**Issue by KSPAtlas** [nohello-net/site#60]
The polish translation uses "Katarzyna" as a name for a  male character when that is a women's name. It also refers to them as a she. Please change the name to a male name like "Kuba" or something.

**Comment by lnowak-preglife** [comment]
I've updated the whole polish translation in #62. Feel free to comment.

**Comment by notjosh** [comment]
I uploaded the changes from #62 to Transifex, and made them live via #63! 🥳
